export const Productos = [
    {
        id: 1,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/RELOJ%20AMAZFIT%20GTS%202E%20BLACK.jpg?raw=true' ,
        codigo: "W2021OV1N",
        descripcion: "RELOJ AMAZFIT GTS 2E BLACK - 1.65''",
        marca: "AMAZFIT",
    },
    {
        id: 2,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/HUAWEI%20WATCH%20GT%202%20SPORT%201.39%22%20CAJA%2046MM.jpg?raw=true' ,
        codigo: "LTN-B19",
        descripcion: "HUAWEI WATCH GT 2 SPORT 1.39' CAJA 46MM",
        marca: "HUAWEI",
    },
    {
        id: 3,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/HUAWEI%20RELOJ%20HONOR%20GS%20PRO%20KAN-B19.jpg?raw=true' ,
        codigo: "697245316936",
        descripcion: "HUAWEI RELOJ HONOR GS PRO KAN-B19",
        marca: "HUAWEI",
    },
    {
        id: 4,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20WATCH%20SERIE%20SE%2044MM%20SILVER%20MKQ43LL.jpg?raw=true' ,
        codigo: "MKQ43LL/A",
        descripcion: "APPLE WATCH SERIE SE 44MM SILVER MKQ43LL/A",
        marca: "APPLE",
    },
    {
        id: 5,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20WATCH%20SERIE%207%2045MM%20MIDNIGHT.jpg?raw=true' ,
        codigo: "MKN53LL/A",
        descripcion: "APPLE WATCH SERIE 7 45MM MIDNIGHT",
        marca: "APPLE",
    },
    {
        id: 6,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20WATCH%20SERIE%207%2041MM%20STARLIGHT.jpg?raw=true' ,
        codigo: "MKMY3LL/A",
        descripcion: "APPLE WATCH SERIE 7 41MM STARLIGHT",
        marca: "APPLE",
    },
    {
        id: 7,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE7%2045MM%20STARLIGHT.jpg?raw=true' ,
        codigo: "MKN63LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE7 45MM STARLIGHT",
        marca: "APPLE",
    },
    {
        id: 8,
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE7%2041MM%20MIDNIGHT.jpg?raw=true' ,
        codigo: "MKMX3LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE7 41MM MIDNIGHT",
        marca: "APPLE",
    },
    {
        id: 9,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE-SE%2044MM%20SPACEG.jpg?raw=true' ,
        codigo: "MKQ63LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE-SE 44MM SPACEG",
        marca: "APPLE",
    },
    {
        id: 10,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE-SE%2044MM%20SILVER.jpg?raw=true' ,
        codigo: "MYDQ2LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE-SE 44MM SILVER",
        marca: "APPLE",
    },
    {
        id: 11,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE-SE%2040MM%20SPACEG.jpg?raw=true' ,
        codigo: "MKQ13LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE-SE 40MM SPACEG",
        marca: "APPLE",
    },
    {
        id: 12,
        categoria: "reloj",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/relojes/APPLE%20RELOJ%20IWATCH%20SERIE%203%2042MM%20SPACEGR.jpg?raw=true' ,
        codigo: "MTF32LL/A",
        descripcion: "APPLE RELOJ IWATCH SERIE 3 42MM SPACEGR",
        marca: "ADATA",
    }
,
    {
        id: 13,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20NSX%20EPSILON%20CEL%208GB%20SSD480%20W10%20NSX%20NOTEBOOK.jpg?raw=true',
        codigo: "NCF4S4W-2",
        descripcion: "NOTEBOOK NSX EPSILON CEL 8GB SSD480 W10 NSX NOTEBOOK",
        marca: "NSX",
    },
    {
        id: 14,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20NSX%20EPSILON%20CEL%208GB%20SSD480%20FREE.jpg?raw=true' ,
        codigo: "NCF4S4F-2",
        descripcion: "NOTEBOOK NSX EPSILON CEL 8GB SSD480 FREE",
        marca: "NSX",
    },
    {
        id: 15,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20NSX%20EPSILON%20CEL%208GB%20SSD120%20W10.jpg?raw=true' ,
        codigo: "ASX6000LNP51",
        descripcion: "NOTEBOOK NSX EPSILON CEL 8GB SSD120 W10",
        marca: "NSX",
    },  {
        id: 16,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20HP%20PAVILION%20X360%20CONVERTIBLE%2014.jpg?raw=true' ,
        codigo: "9UV81LA",
        descripcion: "NOTEBOOK HP PAVILION X360 CONVERTIBLE 14",
        marca: "HP",
    },
    {
        id: 17,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20HP%20240G8%20CELN4020%2014%204GB-500W10.jpg?raw=true' ,
        codigo: "2Q9S5LT",
        descripcion: "NOTEBOOK HP 240G8 CELN4020 14 4GB/500W10",
        marca: "HP",
    },
    {
        id: 18,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20NSX%20EPSILON%20CLOUD%204GBRAM%2064GB%20FREEDOS.jpg?raw=true' ,
        codigo: "ASX6000LNP51",
        descripcion: "NOTEBOOK NSX EPSILON CLOUD 4GBRAM 64GB FREEDOS",
        marca: "NSX",
    },
    {
        id: 19,
        categoria: "notebook",
        img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/NOTEBOOK%20APPLE%20MACBOOK%20PRO%2013''%208%20CORE%20M1%20CHIP%20512GB%20SSD%20SILVER.jpg?raw=true",
        codigo: "MYDC2LE/A",
        descripcion: "NOTEBOOK APPLE MACBOOK PRO 13'' 8 CORE M1 CHIP 512GB SSD SILVER",
        marca: "APPLE",
    },
    {
        id: 20,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/MACBOOK%20PRO%2013%22%20TOUCH%20BAR%20M1%20512%20GB%20-%20SPACE%20GRAY.jpg?raw=true' ,
        codigo: "MYD92LE/A",
        descripcion: "MACBOOK PRO 13'' TOUCH BAR M1 512 GB - SPACE GRAY",
        marca: "APPLE",
    },
    {
        id: 21,
        categoria: "notebook",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/notebooks/APPLE%20MACBOOK%20PRO%202020,M1,%20256%20GB%20DE%20SSD,%208%20GB%20DE%20RAM%20GRIS%20ESPACIAL.jpg?raw=true' ,
        codigo: "MYD82LE/A",
        descripcion: "APPLE MACBOOK PRO 2020,M1, 256 GB DE SSD, 8 GB DE RAM GRIS ESPACIAL",
        marca: "APPLE",
    }
,
    {
        id: 22,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/TABLET%20SAMSUNG%20GALAXY%20TAB%20S6%20LITE%20SM-P615%2010.4%20CON%20RED%20M%C3%93VIL%2064GB%20OXFORD%20GRAY%20CON%204GB%20DE%20MEMORIA%20RAM.jpg?raw=true',
        codigo: "SM-P615NZAUA",
        descripcion: "TABLET SAMSUNG GALAXY TAB S6 LITE SM-P615 10.4 CON RED MÓVIL 64GB OXFORD GRAY CON 4GB DE MEMORIA RAM",
        marca: "SAMSUNG"
    },
    {
        id: 23,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/TABLET%20LENOVO%20LTE%20K10%20TB-X6C6%203G+32GBE.jpg?raw=true' ,
        codigo: "ZA8R0018AR",
        descripcion: "TABLET LENOVO LTE K10 TB-X6C6 3G+32GBE",
        marca: "LENOVO",
    },
    {
        id: 24,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/APPLE%20IPAD%20PRO%2012.9IN%20256GB%20M1%205TA%20GEN.jpg?raw=true' ,
        codigo: "MHNH3LE/A",
        descripcion: "APPLE IPAD PRO 12.9IN 256GB M1 5TA GEN",
        marca: "APPLE",
    },
    {
        id: 25,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/APPLE%20IPAD%20MINI%2064GB%20SPACE%20GREY%206GEN.jpg?raw=true' ,
        codigo: "MK7M3LE/A",
        descripcion: "APPLE IPAD MINI 64GB SPACE GREY 6GEN",
        marca: "APPLE",
    },
    {
        id: 26,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/IPAD%20PRO%2011%22%20CHIP%20M1%20WI-FI%20-128GB%20(3RA%20GEN)-%20SPACE%20GRAY.jpg?raw=true' ,
        codigo: "MHQR3LE/A",
        descripcion: "IPAD PRO 11'' CHIP M1 WI-FI -128GB (3RA GEN)- SPACE GRAY",
        marca: "APPLE",
    },
    {
        id: 27,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/TABLET%20CON%20FUNDA%20SAMSUNG%20GALAXY%20TAB%20ACTIVE2%202017%208%20CON%20RED%20M%C3%93VIL%2016GB%20BLACK%20CON%203GB%20DE%20MEMORIA%20RAM.jpg?raw=true' ,
        codigo: "SM-T395NZKAA",
        descripcion: "TABLET CON FUNDA SAMSUNG GALAXY TAB ACTIVE2 2017 8 CON RED MÓVIL 16GB BLACK CON 3GB DE MEMORIA RAM",
        marca: "SAMSUNG",
    },
    {
        id: 28,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/APPLE%20IPAD%20MINI%20256GB%206GE%20SPACE%20GREY%20LA.jpg?raw=true' ,
        codigo: "MK7T3LE/A",
        descripcion: "APPLE IPAD MINI 256GB 6GE SPACE GREY LA",
        marca: "APPLE",
    },
    {
        id: 29,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/APPLE%20IPAD%20AIR4%2064GB%2010,9%20SPACE%20GRAY.jpg?raw=true' ,
        codigo: "MYFM2LE/A",
        descripcion: "APPLE IPAD AIR4 64GB 10,9 SPACE GRAY",
        marca: "APPLE",
    }, 
    {
        id: 30,
        categoria: "tablet",
        img: 'https://github.com/FabricioGodoy/imagenes/blob/main/productos/tablet/APPLE%20IPAD%20AIR4%20256GB%2010,9%20SPACE%20GRAY.jpg?raw=true' ,
        codigo: "MYFT2LE/A",
        descripcion: "APPLE IPAD AIR4 256GB 10,9 SPACE GRAY",
        marca: "APPLE",
    }

]

